substitutions:
  name: home-assistant-voice-0913b7
  friendly_name: Home Assistant Voice 0913b7
packages:
  Nabu Casa.Home Assistant Voice PE: github://esphome/home-assistant-voice-pe/home-assistant-voice.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret Home_Assistant_Voice_0913b7_api_encryption_key


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
