# Variables
substitutions:
  device_name: ""
  # Default the friendly_name to the required device_name
  friendly_name: "${device_name}"
  esphome_project_name: ""
  esphome_project_version: ""
  api_encryption_key: ""
  fallback_ap_password: ""
  ota_password: ""
  wifi_password: ""
  wifi_ssid: ""

# https://esphome.io/components/esphome
esphome:
  name: "${device_name}"
  # Set friendly_name so Home Assistant use it to prefix entity names
  # so they'll be unique to each device.
  # https://esphome.io/components/esphome.html#configuration-variables
  friendly_name: "${friendly_name}"
  project:
    name: "${esphome_project_name}"
    version: "${esphome_project_version}"

# https://esphome.io/guides/creators#relevant-documentation
dashboard_import:
  package_import_url: github://andyattebery/esphome-config/templates/base.yaml
  import_full_config: false

# Enable Home Assistant API
# https://esphome.io/components/api
api:
  encryption:
    key: "${api_encryption_key}"

# Enable over-the-air updates
# https://esphome.io/components/ota
ota:
  platform: esphome
  password: "${ota_password}"

# Set WiFi credentials
# https://esphome.io/components/wifi
wifi:
  ssid: "${wifi_ssid}"
  password: "${wifi_password}"
  min_auth_mode: WPA2

  # Enable fallback access point in case wifi connection fails
  ap:
    ssid: "${device_name}-Fallback-AP"
    password: "${fallback_ap_password}"

# Enable captive portal for fallback access point
# https://esphome.io/components/captive_portal
captive_portal:
