# Variables
substitutions:
  esphome_project_name: "KMC.SmartOutlet"
  esphome_project_version: "1.0"

# https://esphome.io/guides/configuration-types#packages
packages:
  base: !include base.yaml

# https://esphome.io/components/esp8266.html
esp8266:
  board: esp01_1m
  restore_from_flash: true
# https://esphome.io/guides/creators#relevant-documentation
dashboard_import:
  package_import_url: github://andyattebery/esphome-configs/packages/kmc-smart-outlet.yaml
  import_full_config: false

# https://esphome.io/components/binary_sensor/
binary_sensor:
  # https://esphome.io/components/binary_sensor/gpio
  - platform: gpio
    pin:
      number: GPIO16
      mode: INPUT
      inverted: true
    name: "Button"
    on_press:
      - switch.toggle: relay1
      - switch.toggle: relay2
      - switch.toggle: relay3
  # https://esphome.io/components/binary_sensor/status
  - platform: status
    name: "Status"

# Enable logging
# https://esphome.io/components/logger
logger:

# Configure sensors
# https://esphome.io/components/sensor/
sensor:
  # https://esphome.io/components/sensor/hlw8012.html
  - platform: hlw8012
    sel_pin: GPIO12
    cf_pin: GPIO4
    cf1_pin: GPIO5
    current:
      name: "Current"
      accuracy_decimals: 5
    voltage:
      name: "Voltage"
      accuracy_decimals: 5
    power:
      name: "Power"
      accuracy_decimals: 5
    energy:
      name: "Energy"
      accuracy_decimals: 5
    update_interval: 60s
    current_resistor: 0.0028
    voltage_divider: 2150
    change_mode_every: 4
    initial_mode: CURRENT
  # https://esphome.io/components/sensor/wifi_signal
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

# Configure status LED
# https://esphome.io/components/light/status_led
status_led:
  pin:
    number: GPIO1
    inverted: false

# Configure switches
# https://esphome.io/components/switch/
switch:
  # https://esphome.io/components/switch/gpio
  - platform: gpio
    name: "Switch 1"
    pin: GPIO15
    id: relay1
    restore_mode: RESTORE_DEFAULT_ON
  - platform: gpio
    name: "Switch 2"
    pin: GPIO13
    id: relay2
    restore_mode: RESTORE_DEFAULT_ON
  - platform: gpio
    name: "Switch 3"
    pin: GPIO14
    id: relay3
    restore_mode: RESTORE_DEFAULT_ON
