# Variables
substitutions:
  esphome_project_name: "Sonoff.S31"
  esphome_project_version: "1.0"
  update_interval: 60s

# https://esphome.io/guides/configuration-types#packages
packages:
  base: !include base.yaml

# https://esphome.io/components/esp8266.html
esp8266:
  board: esp01_1m
  restore_from_flash: true
# https://esphome.io/guides/creators#relevant-documentation
dashboard_import:
  package_import_url: github://andyattebery/esphome-config/templates/sonoff-s31.yaml
  import_full_config: false

# https://esphome.io/components/binary_sensor/
binary_sensor:
  # https://esphome.io/components/binary_sensor/gpio
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Button"
    on_press:
      - switch.toggle: relay
  # https://esphome.io/components/binary_sensor/status
  - platform: status
    name: "Status"

# Enable logging
# https://esphome.io/components/logger
logger:
  # Disable UART logging (UART logging interferes with cse7766)
  baud_rate: 0

# https://esphome.io/components/sensor/
sensor:
  # https://esphome.io/components/sensor/cse7766.html
  - platform: cse7766
    current:
      name: "Current"
      accuracy_decimals: 5
      filters:
        - throttle_average: ${update_interval}
    voltage:
      name: "Voltage"
      accuracy_decimals: 5
      filters:
        - throttle_average: ${update_interval}
    power:
      name: "Power"
      accuracy_decimals: 5
      filters:
        - throttle_average: ${update_interval}
    energy:
      name: "Energy"
      accuracy_decimals: 5
      filters:
        - throttle: ${update_interval}
    apparent_power:
      name: Apparent Power
      accuracy_decimals: 5
      filters:
        - throttle_average: ${update_interval}
    power_factor:
      name: Power Factor
      accuracy_decimals: 5
      filters:
        - throttle_average: ${update_interval}
  # https://esphome.io/components/sensor/wifi_signal
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

# https://esphome.io/components/switch/
switch:
  # https://esphome.io/components/switch/gpio
  - platform: gpio
    name: "Switch"
    pin: GPIO12
    id: relay
    restore_mode: RESTORE_DEFAULT_ON

# https://esphome.io/components/light/status_led
status_led:
  pin: GPIO13

# https://esphome.io/components/uart
uart:
  rx_pin: RX
  baud_rate: 4800
  parity: EVEN
