substitutions:
  device_name: "shop-04-outlet"
  friendly_name: "shop-04 Outlet"
  api_encryption_key: !secret shop_04_outlet_api_encryption_key
  fallback_ap_password: !secret shop_04_outlet_fallback_ap_password
  ota_password: !secret shop_04_outlet_ota_password
  wifi_password: !secret wifi_password
  wifi_ssid: !secret wifi_ssid

packages:
  remote_package:
    url: https://github.com/andyattebery/esphome-config
    files:
      - templates/sonoff-s31.yaml
  base_offsite: !include packages/base-offsite.yaml
